### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by jimchen1980** [micromaomao/schsrch#2]
Hi, I am wondering if you could provide a detailed installation tutorial for your project since the documentation is nearly non-existent. thanks

**Comment by micromaomao** [comment]
Can I know why would you want to install another instance of this website?

The problem is, this project (as well as the base project [maowtm.org](https://github.com/micromaomao/maowtm.org) which act as the server) isn't designed for others to run -- it is not easy to set up and there may be hard-coded domain names in the project code. I publish the source code for others to reference but was not intending it to be run elsewhere (largely because I don't see why other people want to host their own version of this search engine or my personal website). So I'm afraid I may not be able to provide such tutorial unless running another instance of this website is necessary because of some specific requirements, etc.

**Comment by jimchen1980** [comment]
okay, and if I may know the method you identify each question?

**Comment by micromaomao** [comment]
Basicially by looking for numbers that appear on the left of each page…

[Relevant code is here](https://github.com/micromaomao/schsrch/blob/master/lib/recognizer.js#L50), although I would admit that it is not exactly well written and may be hard to understand. I can organize it and add more comments if you wish.

**Comment by jimchen1980** [comment]
I suggest that if you could add a tag system to tag the category of each question would be more than helpful. Furthermore, a statistical system could be built upon it to analyze student's performance in different subject areas

**Comment by jimchen1980** [comment]
Also, i think using OpenCV Cascade Classifier would be a better solution of pinpointing the location of each question

**Comment by micromaomao** [comment]
Yeah, a tag system (and, perhaps, a statistical system) may be useful, I don't know. A teacher has once suggested me to build such system before, but unfortunately I don't have that much spare time to code it, and I don't see it as exactly necessary since many of us students need to do the work on paper, and we can keep our record on paper.

**Comment by micromaomao** [comment]
About the determining the position of questions thing, I think the current approach is kind of good enough… And I haven't yet get the time (and the determination) to learn some machine learning stuff to be able to rewrite this with some sort of classifier. However I will consider learning it later and your suggestion of using OpenCV may be worth considering. (Although I do think that because these papers are not really images but pieces of text, OpenCV and other image recognition technologies may not be the best choice). Nevertheless, thank you for the feedback.
